name: MazeMind Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Check Python syntax
      run: python -m compileall .

    - name: Notify Discord on success
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content": "Build erfolgreich auf `main`"}' \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord on failure
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{"content": "Build fehlgeschlagen auf `main`"}' \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
